class MyLocators():

    rootDriver = "/Users/EmilianoCabreraPerez/Downloads/chromedriver"
    URL = "https://rahulshettyacademy.com/AutomationPractice/"
    XPath_enterMessage = "/html/body/h1"
    XPath_suggessionClassExample = "/html/body/div[1]/div[2]/fieldset/input"
    XPath_countrieMexico = "/html/body/ul/li[6]/div"
    XPath_option_2 = "/html/body/div[1]/div[3]/fieldset/select/option[3]"
    XPath_option_3 = "/html/body/div[1]/div[3]/fieldset/select/option[4]"
    XPath_switchWindowExample = "/html/body/div[2]/div[1]/fieldset/button"
    XPath_secondPopUp = "/html/body/div[4]/div[2]/div/div/div/span/div/div[6]/div/div/button"
    XPath_30DaysMoneyBack = "/html/body/section[3]/div/div/div/div[5]/div/div[2]/div/div[2]/h3"
    XPath_switchTabExample = "/html/body/div[2]/div[2]/fieldset/a"
    XPath_ViewAllCourses = "/html/body/app-root/div/app-home/div/section[2]/div[2]/a"
    XPath_switchToAlertExample = "/html/body/div[2]/div[3]/fieldset/input[1]"
    XPath_alertButton = "/html/body/div[2]/div[3]/fieldset/input[2]"
    XPath_confirmButton = "/html/body/div[2]/div[3]/fieldset/input[3]"
    XPath_webTableExample = "/html/body/div[3]/div[1]/fieldset/table/tbody/tr"
    XPath_webTableFixedHeader = "/html/body/div[3]/div[2]/fieldset[2]/div[1]/table/tbody/tr"
    XPath_iFrame = "/html/body/div[5]/fieldset/iframe"
    XPath_iFrameMessage = "/html/body/app-root/div/app-home/div/section[4]/div/div/div/div[2]/ul/li[5]"
    saveRootImage = "/Users/EmilianoCabreraPerez/Documents/Python/Stori/Reports/Test_Stori.png"